{% set version = "0.5.4" %}  
{% set sha256 = "4cb2f493947e235c51b62271a370b373282c105414ef7e36eba7624d658e18f4" %}

package:
  name: segysak
  version: {{ version }}

source:
  url: https://github.com/trhallam/segysak/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --disable-pip-version-check
  script_env:
   - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
   - segysak = segysak._cli:cli

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - numpy >=1.20
    - pandas
    - matplotlib
    - segyio
    - xarray
    - dask
    - distributed
    - tqdm
    - scipy !=1.10.0
    - click
    - h5netcdf
    - addict
    - more-itertools >=8.0
    - typing-extensions
    - loguru

test:
  requires:
    - pip
  commands:
    - pip check
    - segysak --help

  imports:
    - segysak
    - segyio.segy

about:
  home: https://github.com/trhallam/segysak
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "A library for reading, writing, and processing SEG-Y seismic data."
  description: |
    Segysak is a Python library that simplifies reading, writing, and processing SEG-Y seismic files, 
    with a focus on convenience and performance.
  dev_url: https://github.com/trhallam/segysak/tree/main
  doc_url: https://trhallam.github.io/segysak/latest/

extra:
  services:
    recipe-maintainers:
       - bkreider
    comment: "https://anaconda.zendesk.com/agent/tickets/49247"

